# Generated by Django 4.2.6 on 2023-10-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_description_remove_task_important_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='datecompleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='centro_costos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='departamento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='ml',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='nombre_pc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='nombre_user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='sede',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='task',
            table='registro',
        ),
    ]
