# Generated by Django 4.2.6 on 2023-10-10 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_task_created_task_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='cedula',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='centro_costos',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='departamento',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='ml',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='nombre_pc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='nombre_user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='sede',
            field=models.CharField(default='', max_length=50),
        ),
    ]
