# Generated by Django 4.2.6 on 2023-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_user_alter_task_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ml',
            field=models.CharField(default='', max_length=50),
        ),
    ]
