# Generated by Django 4.2.6 on 2023-10-12 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fecha_busqueda',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
