# Generated by Django 4.2.6 on 2023-10-17 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_fecha_busqueda'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml', models.CharField(default='', max_length=50)),
                ('nombre_pc', models.CharField(default='', max_length=50)),
                ('nombre_user', models.CharField(default='', max_length=50)),
                ('cedula', models.IntegerField(default=0)),
                ('centro_costos', models.CharField(default='', max_length=50)),
                ('departamento', models.CharField(default='', max_length=50)),
                ('sede', models.CharField(default='', max_length=50)),
                ('fecha_busqueda', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='task',
            name='centro_costos',
        ),
        migrations.RemoveField(
            model_name='task',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='task',
            name='fecha_busqueda',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ml',
        ),
        migrations.RemoveField(
            model_name='task',
            name='nombre_pc',
        ),
        migrations.RemoveField(
            model_name='task',
            name='nombre_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sede',
        ),
    ]
