# Generated by Django 4.2.6 on 2023-10-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_registro_regis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regis',
            name='fecha_busqueda',
        ),
    ]
