# Generated by Django 4.2.6 on 2023-11-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_userrole_userprofile_task_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regis',
            name='sede',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
