# Generated by Django 4.2.6 on 2023-11-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='role_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.userrole'),
        ),
    ]
